version: '3.1'

services:

  postgres:
    # build: .
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ikatoo
      POSTGRES_PASSWORD: ikatoo123
      POSTGRES_DB: ikatoo

  adminer:
    image: adminer
    ports:
      - 8080:8080