version: '3.1'

services:

  node:
    build: {
      context: "..",
      dockerfile: "docker/Dockerfile"
    }
    command: "yarn start"
    working_dir: /home/node/app
    environment:
      NODE_ENV: prod
      POSTGRES_USER: ikatoo
      POSTGRES_PASSWORD: ikatoo123
      POSTGRES_DB: ikatoo
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    links:
      - postgres
    expose:
      - "8000"
    ports:
      - "8001:8000"

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ikatoo
      POSTGRES_PASSWORD: ikatoo123
      POSTGRES_DB: ikatoo

  adminer:
    image: adminer
    ports:
      - 8080:8080