version: '3.1'

services:

  postgres:
    build: .
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ikatoo123
      POSTGRES_DB: ikatoo

  adminer:
    image: adminer
    ports:
      - 8080:8080